---
ansible_python_interpreter: python3

docker_userns_remap_enable: yes

gitlab_userns_remap_enable: yes

gitlab_ssh_port: 22022

gitlab_monitoring_whitelist:
  - 0.0.0.0/0

gitlab_email_enabled: yes
gitlab_email_from_mailbox: gitlab@test
gitlab_email_from_display_name: GitLab
gitlab_email_reply_to_mailbox: noreply@test
gitlab_email_smtp_server_host: smtp.test
gitlab_email_smtp_server_port: 465
gitlab_email_smtp_transport_security: tls
gitlab_email_smtp_ca_cert: cert.pem
gitlab_email_smtp_user_auth_method: plain
gitlab_email_smtp_user_name: gitlab
gitlab_email_smtp_user_password: 'Pa$$w0rD'
