---
ansible_python_interpreter: python3

docker_config:
  userns-remap: default

gitlab_userns_remap_enable: yes

gitlab_ssh_port: 22022

gitlab_workers: 2
gitlab_min_threads: 4
gitlab_max_threads: 4

gitlab_monitoring_whitelist:
  - 0.0.0.0/0
