---
version: "3.7"
services:
  gitlab:
    build:
      context: ./build
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # URL
        external_url 'http://gitlab.test'
        registry_external_url 'http://gitlab.test:5050'

        # HTTPS

        # Application server

        # Monitoring

        # Outgoing emails
        gitlab_rails['gitlab_email_enabled'] = false

        # Backup
    volumes:
      - type: volume
        source: config
        target: /etc/gitlab
      - type: volume
        source: data
        target: /var/opt/gitlab
      - type: volume
        source: log
        target: /var/log/gitlab
    networks:
      - bridge
    ports:
      - protocol: tcp
        target: 80
        published: 80
      - protocol: tcp
        target: 22
        published: 22
      - protocol: tcp
        target: 5050
        published: 5050
    restart: always
volumes:
  config:
  data:
  log:
networks:
  bridge:
    driver: bridge
